version: 2.0

jobs:
  install_and_build:
    machine: true
    
    steps:
      - checkout
      - run:
          name: run docker
          command: |
            docker build -t example-app .
            docker run -d -p 5000:5000 -t example-app 
            echo "Testing"
      - run:
          name: Run flake8
          command: |
            docker_id=$(docker ps -a |grep example-app|awk '{print $1}')
            docker exec -it ${docker_id} sh -c "pip3 install -U flake8"
            docker exec -it ${docker_id} sh -c "flake8 /app/app.py"

      - run:
          name: Run tests
          command: |
            docker_id=$(docker ps -a |grep example-app|awk '{print $1}')
            docker exec -it ${docker_id} sh -c "python3 /app/tests.py"

  deploy_in_staging:
    machine: true

    steps:
      - checkout
      - run:
          name: run docker
          command: |
            docker build -t example-app .
            docker run -d -p 5000:5000 -t example-app

      - run:
          name: Run build docker
          command: |
            eval $(aws ecr get-login --no-include-email --region ${AWS_REGION})
            docker tag example-app:latest ${ECR_ENDPOINT_STAG}:${CIRCLE_SHA1}
            docker push ${ECR_ENDPOINT_STAG}:${CIRCLE_SHA1}

      - run:
          name: kubectl deployment here
          command: |
            bash -x deploy_hooks/script.sh

  deploy_in_production:
    machine: true

    steps:
      - checkout
      - run:
          name: run docker
          command: |
            docker build -t example-app .
            docker run -d -p 5000:5000 -t example-app

      - run:
          name: Run build docker
          command: |
            eval $(aws ecr get-login --no-include-email --region ${AWS_REGION})
            docker tag example-app:latest ${ECR_ENDPOINT_PROD}:${CIRCLE_TAG}
            docker push ${ECR_ENDPOINT_PROD}:${CIRCLE_TAG}

      - run:
          name: kubectl deployment here
          command: |
            bash -x deploy_hooks/script.sh

workflows:
  version: 2

  build-only:
    jobs:
      - install_and_build:
          filters:
            branches:
              ignore:
                - master
                - /feature\/.*
 
  build-and-deploy-production:
    jobs:
      - install_and_build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
  
      - deploy_in_production:
          requires:
            - install_and_build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  build-and-deploy-staging:
    jobs:
      - install_and_build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - master
                - /feature\/.*

      - deploy_in_staging:
          requires:
            - install_and_build
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - master
                - /feature\/.*
