version: 2.0

jobs:
  install_and_build:
    machine: true
    
    steps:
      - checkout
      - run:
          name: run docker
          command: |
            docker build -t example-app .
            docker run -d -t example-app 
      - run:
          name: Run flake8
          command: |
            docker_id=$(docker ps -a |grep example-app|awk '{print $1}')
            docker exec -it ${docker_id} sh -c pip3 install -U flake8
            docker exec -it ${docker_id} sh -c flake8 /app/app.py

      - run:
          name: Run tests
          command:
            docker_id=$(docker ps -a |grep example-app|awk '{print $1}')
            docker exec -it ${docker_id} sh -c python3 /app/app.py

workflows:
  version: 2
  build-and-deployments:
    jobs:
      - install_and_build
